### PR TITLE
Fix heading contrast in hero section

### PR DESCRIPTION
**Pull request by Mosaab-Emam**
Closes [firecamp#112](https://github.com/firecamp-dev/firecamp/issues/112)
Closes [website#13](https://github.com/firecamp-dev/website/issues/13)

**Preview**
Screenshot from 2023-10-21 11-24-48

**Note**
This color gradient is only applied in dark mode. The contrast in light mode is not that bad.

**Description**
To achieve this, I separated the heading to it's own _client component_ because it depends on the _theme_ value.
To create the gradient, I took the colors from the gradient in the firecamp logo, then I selected the closest colors to them that are available in tailwind. I used those classes to dynamically apply the gradient when dark mode is active (for better contrast). I maintained the original gradient to be used in light mode.

### CODE REVIEW

**Comment by Nishchit14** [comment]
We have decided to keep this [theme colors ](https://github.com/firecamp-dev/website/pull/12/files#diff-9274dd6fc8c651f20eadbacc7b1e731acd8953b378090acbacd2e5030817bc40) for now, if it's quick then you can implement. I want to merge the PR as quickly as possible.

**Comment by Mosaab-Emam** [comment]
Our PRs do not necessarily conflict. My chosen colors only apply to dark mode, the slate colors can be applied in light mode.
I can update the PR to achieve this if you want, or I can just close if my contribution is not suitable.

**Comment by Mosaab-Emam** [comment]
Integrated values from [website#12](https://github.com/firecamp-dev/website/pull/12)

**Comment by Nishchit14** [comment]
@Mosaab-Emam It still the orange theme
https://firecamp-l0zwh23gb-firecamp.vercel.app/

image

**Comment by Nishchit14** [comment]
#12 is merged, you can fix it on top of it.

**Comment by Nishchit14** [comment]
@Mosaab-Emam can you please resolve the conflicts?

**Comment by Mosaab-Emam** [comment]
Ok

**Comment by Mosaab-Emam** [comment]
**Update:**

Due to `next-theme` only working on the server side, I was unable to correctly set the correct gradient on the initial render.

When themes are switched, the correct values will be set, however if the initial render occurs with the dark theme active then the gradient value will be set incorrectly.

This is unacceptable to me, yet I could not resolve it using the current theming solution. Therefore I will close this PR.

**Pull request closed without merging**
